name: CI

on: [push]

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11 x64
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - name: Run Detekt
        run: ./gradlew :detekt
      - name: Run JUnit
        run: ./gradlew :test